version: 2

sources:
  - name: public
    database: warehouse
    schema: public
    tables:
      - name: customers
      - name: products
      - name: transactions

models:
  - name: stg_customers
    description: "Staged customer data"
    columns:
      - name: customer_id
        tests: [unique, not_null]
      - name: email
        tests: [not_null]
      - name: gender
        tests: [not_null]
      - name: country_name
        tests: [not_null]
      - name: signup_date
        tests: [not_null]

  - name: stg_products
    description: "Staged product data with duplicate removed"
    columns:
      - name: product_id
        tests: [unique, not_null]
      - name: product_name
        tests: [not_null]
      - name: category
        tests: [not_null]
      - name: price_gbp
        tests: [not_null]

  - name: stg_transactions
    description: "Staged transaction data"
    columns:
      - name: transaction_id
        tests: [unique, not_null]
      - name: customer_id
        tests: [not_null]
      - name: product_id
        tests: [not_null]
      - name: quantity
        tests: [not_null]
      - name: transaction_date
        tests: [not_null]
